# Generated by Django 3.2.3 on 2021-05-27 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 12, 15, 59, 150095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1098943-f968-480a-8632-ecefc6bad9a8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 12, 15, 59, 150145, tzinfo=utc)),
        ),
    ]
